### PR TITLE
Add some recommended security headers

### PR DESCRIPTION
**Pull request by yaazkal**
The motivation for this PR is to enhance some security features. This will:

- Set the `Content-Type-Options` to "nosniff" regardless of the response code.
- Add `Strict-Transport-Security` as it _"lets a web site tell browsers that it should only be accessed using HTTPS"_ accordingly to the [documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security).
Must be noted that this adds a basic security layer but is not bullet proof as `Strict-Transport-Security` header is ignored by the browser when the site is accessed using HTTP. Extra steps can be adviced in documentation to use "preload" and manually submit the site to https://hstspreload.org/ (this is not part of the standard). Maybe the `preload` option is a candidate for an extra feature request and has been not added to this PR to prevent breaking sites.
- Add `Referrer-policy` to behave like "Send the origin, path, and querystring when performing a same-origin request, only send the origin when the protocol security level stays the same while performing a cross-origin request (HTTPS→HTTPS), and send no header to any less-secure destinations (HTTPS→HTTP)." accordingly to the [documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy)

I should add that `Content-Security-Policy` header is missing and it's critical. This header is a great compliment for the `X-Xss-Protection` header (an evolution or replacement, but no harm using both).
I think that for greater security and to also prevent the breaking of some sites and legacy content, this should be implemented per site as some [strict policies are recommended](https://csp.withgoogle.com/docs/strict-csp.html). That said, I suggest to include the [scp module](https://www.drupal.org/project/csp) by default and promote its usage and best practices accordingly to the shared link.

Avoid copy/pasting some policies that can be found on some blog posts like
```
add_header Content-Security-Policy default-src https: data: 'unsafe-inline' 'unsafe-eval'" always;
```
as they actually bring no real life effect as you can check on https://csp-evaluator.withgoogle.com

**PS:** This PR does not include `Feature-Policy` header as it is experimental. Also `X-Frame-Options` has been no added as Drupal adds it by default, anyway can be added just to cover other non-drupal sites that can exist, let me know if you want it so I can commit that too.

### CODE REVIEW

**Comment by omega8cc** [comment]
Thank you for the suggestion, but these patches should go to Provision, where Nginx vhost templates reside. The files you propose to patch are of marginal importance and not used by any hosted Drupal site.

**Comment by yaazkal** [comment]
Got it, if you point me to the correct repo I can start the discussion and create a PR if the team agree to

**Comment by yaazkal** [comment]
I'm guessing that is this one https://git.drupalcode.org/project/provision

**Comment by omega8cc** [comment]
The better option would be https://www.drupal.org/project/issues/provision where similar suggestions were discussed already in the past.

**Comment by lhaithaes** [comment]
@yaazkal not sure if you have added to that suggestion to provision tasks?

fyi for anyone else looking for temporary solutions.. Might the worth checking out https://www.drupal.org/project/seckit (not tested on our setup yet)

as suggested https://www.drupal.org/project/csp does exist, but only for d8..( and thats csp rules only)

**Comment by yaazkal** [comment]
hi @lhaithaes I've no made any PR or comment on the provision project. Drupal issue manager is not easy to work with and anyway found this to be like a personal preference rather than a general rule (some will say the other). Thanks for pointing those other projects. My personal opinion is that this is faster at the nginx side that at the app side (php).

Regards !
PS: Closing this PR since has no meaning here like pointed previously.

**Pull request closed without merging**
