### PR TITLE
Yaazkal s3 doc

### PR DESCRIPTION
**Pull request by yaazkal**
see #856

### CODE REVIEW

**Comment by omega8cc** [comment]
Well, this is an optional step and not a requirement. You could use the main AWS account credentials without creating separate user via IAM. Only if you are creating separate user via IAM, you have to set correct permissions, because by default IAM users have no permissions granted.

This should be clarified as an extended how-to / tips section.

**Comment by yaazkal** [comment]
Thanks for the clarification.

Maybe as a security measure it will be better to asign an IAM user, because the account credentials provide unlimited access to all AWS resources. With that IAM will be limited to only S3 (in case the server is compromised). Even it can be better to not asign "All S3 permission" and just the absoluted needed. http://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html

I understand that this is out of the BOA scope, but well, it will be better to work a little more secure.

Fell free to include the words as an advice or best practice suggestion.

Regards !

**Comment by yaazkal** [comment]
As I wrote in this commit, well, there is no need to create an IAM user in order to get the keys, but better to do it as a security practice. I can create another pull request if you want this words better.

**Comment by omega8cc** [comment]
The initial idea was to make it simple. We always prefer the simple way, if only available. The problem with everything from Amazon (AWS, S3, IAM) is that they do everything to make their stuff as hard to understand and use, as possible. At least for people who are not yet fluent in the AWS idiosyncrasies.

If you are using Amazon service for anything beyond S3 buckets for your BOA servers, then sure, access separation is recommended.

But I don't want to add complexity and confuse people who don't need Amazon services for anything else, so they don't really need to even know that IAM exists.

That is why I would prefer to not modify the existing how-to, and instead add the "advanced" section, where we could explain this better.

**Comment by yaazkal** [comment]
Great. As you said, because of the complexity of AWS I felt lost too because I didn't know how to get those keys ids, so I googled and I ended up using IAM. I think, for the simplicity you mention, that it will be good to have the information about how to get those secret id keys then, so maybe adding this can help?

"You can get this keys in the _Security credentials_ link in your AWS console"

or something that let the user know where to get that information, because anyway is not described or clear. Then the IAM thing can be covered in the "advanced" section. (I also recommend a notice and a link to the "advanced" section as an alert in the simple how-to).

Regards !

**Comment by omega8cc** [comment]
If you could submit a clean PR without other unrelated stuff like in this PR, and including your suggestions, we are happy to commit it. Thanks!

**Pull request closed without merging**
