### PR TITLE
add support for nodejs and npm

### PR DESCRIPTION
**Pull request by pricejn2**
creates local npm package repository per user; includes support for users to install bower and/or grunt via npm.

This is an initial stab at #541

Right now, it is bundled in with the CSS XTRA but could be separated out into a totally distinct feature.

### CODE REVIEW

**Comment by pricejn2** [comment]
Also, this doesn't include any docs updates at this stage.

**Comment by pricejn2** [comment]
With this commit, I was able to follow the quick start guide for [Radix](https://www.drupal.org/project/radix)

> Quick start for Drupal 7
> 
> Download and enable radix: drush en radix -y; drush vset theme_default radix
> Create a subtheme: drush cc all; drush radix "Subtheme"
> Set default theme: drush en subtheme -y; drush vset theme_default SUBTHEME_NAME
> Install required modules: cd /path/to/subtheme; npm run setup
> Update browserSyncProxy in /path/to/subtheme/config.json
> Watch: gulp

**Comment by omega8cc** [comment]
Looks good to me, thanks!

If you could open another PR for docs update (including lshell welcome msg) that would be great!

**Comment by omega8cc** [comment]
Also, I think that we don't need to separate it from CSS feature. Unless we want to avoid installing RVM too. Only the current naming convention for the control file could be confusing, though.

**Comment by pricejn2** [comment]
Awesome! There will likely be other npm binaries that will need allowed, but it's a start to just have gulp and bower. 

Thanks for the quick review and commit!

**Comment by omega8cc** [comment]
We need to restrict this feature to Jessie+ perhaps? Since `npm` is not available for Wheezy: https://packages.debian.org/jessie/npm

**Comment by pricejn2** [comment]
In the commit, I utilized the node.js installer script, which automatically creates a sources.list.d repo based on installed distro (see https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions). This removes any distro specific availability problems of npm.

**Comment by omega8cc** [comment]
Yes, I know, sorry for the noise, I added 'scratch that' and deleted my comment :/

**Comment by pricejn2** [comment]
I was halfway through typing my comment when I saw that you deleted yours. Figured someone else may stumble on the note and find it useful so went ahead and posted it. With the noise I've posted over the years, its semi-comforting to see others do the same. 

With respect to the XTRA used, that was my thinking too -- "if one wants CSS features, then let's give them the whole kit and caboodle" which = RVM + NPM at the moment. As individual CSS features drop from mainstream usage, they can be removed from the CSS XTRA or segmented altogether. For now, RVM + Compass is still a widely used and viable (albeit "legacy") option.

**Pull request merged**
