### PR TITLE
add adminer database manager

### PR DESCRIPTION
**Pull request by pricejn2**
- Use Adminer with Nette theme as the default database manager instead of Chive
- Leaves Chive and SQL Buddy options available
- Adds [adminer](https://www.drupal.org/project/adminer) module to `o_contrib_seven` (this portion won't work until the module is added to @omega8cc repo for `get_dev_contrib`)

Addresses #983

### CODE REVIEW

**Comment by pricejn2** [comment]
adminer module support needs additional work.

**Comment by pricejn2** [comment]
With respect to 88a59c0,  I'm not sure if you want to package the necessary items in with the adminer module provided from om8 repo with `get_dev_contrib` or if they should remain separate.

**Comment by omega8cc** [comment]
Great work, thanks!

We need to use our download mirrors for all components, so we never rely on too many remote servers. But we can take care about this, I think.

It also seems that we should package some components to avoid downloading many little files.

Also, we need to make sure that Adminer vhost takes over system IP, so it is removed from Chive vhost, and once you visit system IP in the browser, it displays Adminer instead.

**Comment by pricejn2** [comment]
Awesome, thanks!

Looks like you already caught a few of my misses, including system IP in the Chive vhost.

**Comment by omega8cc** [comment]
@pricejn2 -- It should be complete now, so we can start testing. Thanks again!

**Comment by pricejn2** [comment]
I believe we'll need to use the dev release of adminer module due to https://www.drupal.org/node/2452193

**Comment by omega8cc** [comment]
Hmm.. but does the dev version work? See also: https://www.drupal.org/node/2299301

**Comment by pricejn2** [comment]
I just tested basic functionality with adminer-7.x-1.x-dev and it appears to be working fine.

**Comment by omega8cc** [comment]
Done.

**Pull request merged**
