### PR TITLE
Fixed backboa retrieve logic for remote hosts

### LINKED ISSUE #739: Backboa/Duobackboa "retrieve" command from remote host is not working
There is a mistake in the code: "retrieve" command uses "restore" internal function, so is not working on remote hosts.
I made a patch (pull request) that fixes this issue and the conn_test logic for remote hosts (it was always testing the connection to the same host S3 bucket, not the remote one)

### PR DESCRIPTION
**Pull request by netdream**
Fixes #739 and conn_test for remote hosts

### CODE REVIEW

**Comment by omega8cc** [comment]
Thanks, but the first giant patch doesn't belong here, I think.

**Comment by netdream** [comment]
Uh, yes, sure... it was just the commit f7760c9, don't know why the pool request took also the first one!
Can you just cherry pick the second one or should I can do something else?

**Comment by omega8cc** [comment]
It would be great if you could create new PR, so we could just accept it and attribute properly etc. Thanks!

**Comment by netdream** [comment]
New PR... check #741 . Closing this one

**Pull request closed without merging**
