### PR TITLE
force global for `npm install`

### PR DESCRIPTION
**Pull request by pricejn2**
prevent package installation in unrecognized paths

### CODE REVIEW

**Comment by omega8cc** [comment]
Thanks!

We should replace `npm install -g` with `npm install` in the docs and lshell welcome msg, since we have an alias for it?

**Comment by pricejn2** [comment]
Forcing global may create an unnecessary limitation for certain theme development use cases. I'm thinking it probably makes sense to revert 493da18 and document `npm installl -g` for gulp and bower.

1. If reverted, without the `-g` alias, a `npm install` at `/home/${USER}/` would create a node_modules directory. Any binaries wouldn't be usable, so it probably isn't that big of an issue.
2. If not reverted, we'll also need to alias `npm i` with `npm i -g`.

Thoughts?

**Comment by omega8cc** [comment]
Yes, maybe we should revert https://github.com/omega8cc/boa/commit/0d9b081be80081bb844ab770e19ddef4e76f6476 -- btw, it had a typo breaking remote SSH access: https://github.com/omega8cc/boa/commit/186d781e2d1b748971bdbe1cddf991d895e54050

If we document that people should use `-g` and if they omit it, the result will be just some harmless leftovers, it is fine.

**Comment by pricejn2** [comment]
Apologies for the typo in my commit. Thanks for correcting it.

Agreed. Let's just revert 0d9b081 and stick with documenting `-g` usage.

**Comment by omega8cc** [comment]
Done.

**Pull request merged**
