### PR TITLE
Updates to PHP 5.6.34

### PR DESCRIPTION
**Pull request by yaazkal**
See #1261

### CODE REVIEW

**Comment by dsnopek** [comment]
Cool, thanks for making this PR! I never knew exactly where the versions came from :-)

But this should probably do the update for PHP 7.0.27 -> 7.0.28 too. See [MS-ISAC 2018-023](https://www.cisecurity.org/advisory/multiple-vulnerabilities-in-php-could-allow-for-arbitrary-code-execution_2018-023/):

> Systems affected:
>
> PHP 7.2 prior to 7.2.3
> PHP 7.0 prior to 7.0.28
> PHP 5.0 prior to 5.6.34
> PHP 7.1 prior to 7.1.15

I see there isn't a variable for 7.1 - I guess I hadn't realized that BOA didn't have that yet...

**Comment by yaazkal** [comment]
@dsnopek  I also created #1263 to update PHP from 7.0.27 to 7.0.28

Yes, BOA still not have 7.1 or 7.2

Regards !

**Comment by dsnopek** [comment]
Ah, great, thanks!!!

**Comment by omega8cc** [comment]
Thank you! 👍

**Pull request merged**
