### PR TITLE
Change to dashes in bucket names and upgrade boto/duplicity

### PR DESCRIPTION
**Pull request by pricejn2**
See #1138 and #1141

### CODE REVIEW

**Comment by pricejn2** [comment]
This is only updating the `backboa`. `duobackboa` and docs still need updated.

**Comment by pricejn2** [comment]
I should note that this doesn't seem to work for Wheezy since the Python version is too old. Unless we compile 2.7.9 from sources, 2.7.3 (https://packages.debian.org/wheezy/python) isn't going to cut it.

**Comment by omega8cc** [comment]
We can't introduce changes breaking support for still supported Debian versions, at least until they are completely deprecated (removed) even from major upgrade procedures, so it would require OS-compatibility checks and logic.

**Comment by pricejn2** [comment]
@omega8cc I just tested this on Wheezy and it does in fact work fine building boto from source (as you have it set to do already). The issue I referenced was with pip on python 2.7.3 which is irrelevant to the actual issue and solution.

Also, I've changed the duplicity upgrade version to 0.7.12 instead of 0.7.14. As of 0.7.13 (see http://duplicity.nongnu.org/CHANGELOG), there are two new python dependencies introduced -- https://pypi.python.org/pypi/fasteners and https://pypi.python.org/pypi/monotonic. Until Wheezy (and therefore python 2.7.3) is deprecated from BOA, 0.7.12 is easier to manage.

**Comment by omega8cc** [comment]
Thanks for the explanation. That said, this change will still cause problems we should consider. Existing backups will no longer be accessible via these scripts and will turn into orphaned leftovers, and completely new backups will be created from scratch in new buckets, unless we will rename all existing buckets, which may not work out of the box.

**Comment by pricejn2** [comment]
Very true. As an intermediate solution, we could provide an option whether user wants to use dot (legacy) or dash based bucket naming and direct new installs towards dashes. We can have a verbose warning of the implications of moving from dot to dash (ie, orphaned historical backups). 

A more complete solution something like this would work well and not orphan backups afaik:
1. Specify a `--name` for duplicity.
2. Copy contents of `/root/.cache/duplicity/hash-of-url` to `/root/.cache/duplicity/daily-boa`.
3. Create new S3 bucket and sync old.bucket to new-bucket

**Comment by pricejn2** [comment]
d0aeeb7 is an initial stab at automating the migration from dot to dash buckets

**Comment by omega8cc** [comment]
OK, thanks, I think we can try that. Perhaps also after adding some extra safeguards to make sure the user will not be left w/o access to existing backups if either installing `awscli` fails for some reason, or `aws` commands fail for any reason. You know, it's about backups, so we have to double or triple check that it actually works before automating the procedure.

Before we even commit this to HEAD we have to disable automatic update of these scripts first, because normally they are updated to HEAD version.

Then we could start testing and improving self-healing in the migration procedure.

Or, we could simply leave existing backups as-is and use the new naming convention only for new installs, and then make the migration *optional*.

**Comment by pricejn2** [comment]
Good points all around. I will note that no where are we deleting existing S3 data so there is some redundancy inherent in case things do go wrong (will need some docs so users know to manually delete old.bucket when deemed no longer necessary).

I'll defer to you whether this should be optional. It would be silly to not enforce the dash naming on new installs, but existing (working) installs are a different matter.

**Comment by omega8cc** [comment]
OK, time to move with this forward. We have disabled backboa/duplicity auto-updates by default: https://github.com/omega8cc/boa/commit/5cc6aea10e47c9eb294362c3e1b041ddbdc3f440

**Comment by omega8cc** [comment]
Works as designed, with only small fix: https://github.com/omega8cc/boa/commit/fd63d972cc3f893b4fa3c06cd8cd842ae32de78d

Thanks!

**Pull request merged**
